webtalk_init -webtalk_dir U:/Documents/SPI_CONTROLLER/SPI_CONTROLLER.sim/sim_1/behav/xsim/xsim.dir/spi_mem_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 28 23:20:15 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e693edd2-e243-4f8a-af1f-e75d85223a4c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "84925c06a4f34f29b4340f9c9b1f734a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 8224P 24-Core Processor               " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2546 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "205.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8812_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1078568078 -regid "" -xml U:/Documents/SPI_CONTROLLER/SPI_CONTROLLER.sim/sim_1/behav/xsim/xsim.dir/spi_mem_behav/webtalk/usage_statistics_ext_xsim.xml -html U:/Documents/SPI_CONTROLLER/SPI_CONTROLLER.sim/sim_1/behav/xsim/xsim.dir/spi_mem_behav/webtalk/usage_statistics_ext_xsim.html -wdm U:/Documents/SPI_CONTROLLER/SPI_CONTROLLER.sim/sim_1/behav/xsim/xsim.dir/spi_mem_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
